# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DEPLOY BOT TO THE SERVER

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
  web-deploy:
    needs: build
    name: Deploy bot to the server
    runs-on: ubuntu-latest
    environment: Emoti bot environment
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 176.97.114.179
        username: root
        password: ${{ secrets.SSH_KEY }}
        server-dir: ~/apps/emoticonBot/
        log-level: verbose
      
